name: Update Winget
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['JSON/**.json']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3

      - name: read p81 json
        id: app1
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "JSON/perimeter81.json"

      - name: Run Komac - p81
        uses: michidk/run-komac@v1.1.2
        with:
          komac-version: 1.9.1
          args: 'update --id ${{ steps.app1.outputs.package_id }} --version ${{ steps.app1.outputs.version_number }} --urls ${{ steps.app1.outputs.msi_url }} --submit --token ${{ secrets.GH_TOKEN }}'

      - name: read thy.agent json
        id: app2
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "JSON/DelineaInc.ThycoticAgent.json"
      
      - name: Run Komac - thy.agent
        uses: michidk/run-komac@v1.1.2
        with:
          komac-version: 1.9.1
          args: 'update --id ${{ steps.app2.outputs.package_id }} --version ${{ steps.app2.outputs.version_number }} --urls ${{ steps.app2.outputs.msi_url }} --submit --token ${{ secrets.GH_TOKEN }}'

      - name: read thy.con json
        id: app3
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "JSON/DelineaInc.ThycoticApplicationControlAgent.json"
        
      - name: Run Komac - thy.con
        uses: michidk/run-komac@v1.1.2
        with:
          komac-version: 1.9.1
          args: 'update --id ${{ steps.app3.outputs.package_id }} --version ${{ steps.app3.outputs.version_number }} --urls ${{ steps.app3.outputs.msi_url }} --submit --token ${{ secrets.GH_TOKEN }}'

      - name: read thy.sec json
        id: app4
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "JSON/DelineaInc.ThycoticLocalSecurityAgent.json"
          
      - name: Run Komac - thy.sec
        uses: michidk/run-komac@v1.1.2
        with:
          komac-version: 1.9.1
          args: 'update --id ${{ steps.app4.outputs.package_id }} --version ${{ steps.app4.outputs.version_number }} --urls ${{ steps.app4.outputs.msi_url }} --submit --token ${{ secrets.GH_TOKEN }}'
