name: Update Winget
on:
  workflow_dispatch:
  push:
    paths:
      - 'JSON/**'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.py.outputs.cmd }}
    steps:
      - name: check out repo and run py create output
        uses: actions/checkout@v3
        id: py
      - run: |
          output=$(python ./update.py)
          echo "::set-output name=output1::$output"
        shell: sh

  use_output:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Use the captured output
        run: |
          echo "${{ needs.build.outputs.output1 }}"
          echo "Output successfully accessed"

      - name: Run Komac
        uses: michidk/run-komac@v1.1.1
        with:
          args: '${{ needs.build.outputs.output1 }} --token ${{ secrets.GITHUB_TOKEN }}'