name: Update Winget
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['JSON/*.json']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3

      - name: read p81 json
        id: app1
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "JSON/perimeter81.json"

      - name: Run Komac - p81
        uses: michidk/run-komac@v2.0.1
        with:
          args: 'update -i ${{ steps.app1.outputs.package_id }} -v ${{ steps.app1.outputs.version_number }} --urls ${{ steps.app1.outputs.msi_url }} --submit --token ${{ secrets.GH_TOKEN }}'

      - name: read thy.agent json
        id: app2
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "JSON/DelineaInc.ThycoticAgent.json"

      - name: Run jq and capture output
        id: jq_output
        run: |
          output=$(jq -r '.URI' JSON/DelineaInc.ThycoticAgent.json)
          echo "::set-output name=output::$output"
      
      - name: Run Komac - thy.agent
        uses: michidk/run-komac@v2.0.1
        with:
          args: 'update -i ${{ steps.app2.outputs.product_name }} -v ${{ steps.app2.outputs.version_number }} --urls ${{ steps.jq_output.outputs.output }} --submit --token ${{ secrets.GH_TOKEN }}'

      - name: read thy.con json
        id: app3
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "JSON/DelineaInc.ThycoticApplicationControlAgent.json"
        
      - name: Run Komac - thy.con
        uses: michidk/run-komac@v2.0.1
        with:
          args: 'update -i ${{ steps.app3.outputs.product_name }} -v ${{ steps.app3.outputs.version_number }} --urls ${{ steps.app3.outputs.uri }} --submit --token ${{ secrets.GH_TOKEN }}'

      - name: read thy.sec json
        id: app4
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "JSON/DelineaInc.ThycoticLocalSecurityAgent.json"
          
      - name: Run Komac - thy.sec
        uses: michidk/run-komac@v2.0.1
        with:
          args: 'update -i ${{ steps.app4.outputs.product_name }} -v ${{ steps.app4.outputs.version_number }} --urls ${{ steps.app4.outputs.uri }} --submit --token ${{ secrets.GH_TOKEN }}'
