name: Update Winget
on:
  workflow_dispatch:
  push:
    paths:
      - 'JSON/**'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.py.outputs.cmd }}
    steps:
      - name: check out repo and run py create output
        uses: actions/checkout@v3
        id: py
      - run: |
          python ./update.py
        shell: sh
      - run: echo "${{ needs.build.outputs.output1 }}"

      - name: Run Komac
        uses: michidk/run-komac@v1.1.1
        with:
          args: '${{ needs.build.outputs.output1 }} --token ${{ secrets.GITHUB_TOKEN }}'