name: Update Winget
on:
  workflow_dispatch:
  push:
    paths:
      - 'JSON/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3
      - name: read json
        id: read-json
        run: echo "PACKAGE_JSON=$(jq -c . < JSON/perimeter81.json)" >> $GITHUB_ENV
          

  use_output:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Use the captured output
        run: |
          echo "update --id ${{ fromJson(env.PACKAGE_JSON).id }} --version ${{ fromJson(env.PACKAGE_JSON).version }} --urls ${{ fromJson(env.PACKAGE_JSON).urls }} --submit"
          echo "Output successfully accessed"