name: Run Py Script
on:
  workflow_dispatch:
  schedule:
  - cron: '00 10 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
            cache: 'pip' # caching pip dependencies
        - run: pip install -r requirements.txt

        - name: run py script
          run: python main.py

        - name: Update resources
          uses: test-room-7/action-update-file@v1.8.0
          with:
            file-path: JSON/*.json
            commit-msg: Update resources
            github-token: ${{ secrets.GITHUB_TOKEN }}
