name: Update Winget
on:
  workflow_dispatch:
  push:
    paths:
      - 'JSON/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3

      - name: read json
        id: appJson
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "JSON/perimeter81.json"

      - name: Run Komac
        uses: michidk/run-komac@v1.1.1
        with:
          args: 'update --id ${{ steps.appJson.outputs.package_id }} --version ${{ steps.appJson.outputs.version_number }} --urls ${{ steps.appJson.outputs.msi_url }} --submit --token ${{ secrets.GH_TOKEN }}'