name: Update Winget
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['JSON/*.json']
  workflow_run:
    workflows: ["Run Py Script"]
    types:
      - completed
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.changes_made == 'true') || github.event_name != 'workflow_run' }}
    steps:
      - name: check out repo
        uses: actions/checkout@v3

      - name: read p81 json
        id: app1
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "JSON/perimeter81.json"

      - name: Run Komac - p81
        uses: michidk/run-komac@v2.1.0
        with:
          args: 'update ${{ steps.app1.outputs.package_id }} -v ${{ steps.app1.outputs.version_number }} --urls ${{ steps.app1.outputs.msi_url }} --submit --token ${{ secrets.GH_TOKEN }}'
